### PROFISSIONAIS
### criar um novo profissional

POST http://localhost:3000/profissionais
Content-Type: application/json

{
    "login": "lhf44",
    "senha": "silverstone24",
    "nome": "Lewis Hamilton",
    "registro_profissional": "CRP-202544",
    "status": "ativo"
}

### retornar todos os profissionais:

GET http://localhost:3000/profissionais

### retornar um profissional específico

GET http://localhost:3000/profissionais/1

### atualizar um profissional existente

PATCH http://localhost:3000/profissionais/1
Content-Type: application/json

{
    "senha": "thatsforallkidsallthere"
}

### deletar um profissional existente

DELETE http://localhost:3000/profissionais/1


### ATENDIMENTOS
### criar um novo atendimento

POST http://localhost:3000/atendimentos
Content-Type: application/json

{
  "horario": "2025-01-23T10:00:00.000Z",
  "status": "confirmado",
  "profissional": 2
}

### retornar todos os atendimentos:

GET http://localhost:3000/atendimentos

### retornar um atendimento específico

GET http://localhost:3000/atendimentos/1

### atualizar um atendimento existente

PATCH http://localhost:3000/atendimentos/1
Content-Type: application/json

{
    "status": "não confirmado",
}

### deletar um atendimento existente

DELETE http://localhost:3000/atendimentos/1

### PACIENTES
### criar um novo pacientes

POST http://localhost:3000/pacientes
Content-Type: application/json

{
    "login": "cl16",
    "senha": "ilovemonaco",
    "nome": "Charles Leclerc",
    "sexo": "M",
    "data_nascimento": "1997-10-16",
    "contato": "@charlesleclerc"
}

### retornar todos os pacientes:

GET http://localhost:3000/pacientes

### retornar um paciente específico

GET http://localhost:3000/pacientes/1

### atualizar um paciente existente

PATCH http://localhost:3000/pacientes/1
Content-Type: application/json

{
    "login":"iamstupid"
}

### deletar um paciente existente

DELETE http://localhost:3000/pacientes/1